server:
  port: 8083

spring:
  rabbitmq.host: localhost
  rabbitmq.port: 5672
  rabbitmq.username: guest
  rabbitmq.password: guest
  main:
    allow-bean-definition-overriding: true

rabbitmq:
  target:
    queue: job_queue
    topic: pub_sub_topic
    rpc: rpc_topic